# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KnowTree' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KnowTree

  target 'KnowTreeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KnowTreeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
